#!/bin/bash

RED="\033[0;31m"
GREEN="\033[0;32m"
NC='\033[0m'

# install and setup pyenv if not installed
if ! command -v pyenv &> /dev/null
then
  # auto install from https://github.com/pyenv/pyenv
  curl https://pyenv.run | bash

  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
  echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  exit
fi
printf "${GREEN}Success: ${NC}Pyenv installed\n"

# setup virtualenv
pyenv virtualenv 3.10 bsc

# get requirements
pip install -r requirements.txt

# make bash scripts executable
chmod +x setup
chmod +x run

printf "${GREEN}Success: ${NC}Environment setup\n"
