#!/bin/bash

RED="\033[0;31m"
GREEN="\033[0;32m"
NC='\033[0m'

# install and setup pyenv if not installed
if ! command -v pyenv &> /dev/null
then
  # auto install from https://github.com/pyenv/pyenv
  curl https://pyenv.run | bash

  # add pyenv to path and enable auto-activation of virtualenv
  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
  echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  echo '$(pyenv virtualenv-init -)' >> ~/.bashrc
  exec "$SHELL"

  exit
fi
printf "${GREEN}Success:${NC} Pyenv installed\n"

# install and setup pyenv-virtualenv if not installed
if ! [ -d $(pyenv root)/plugins/pyenv-virtualenv ] &> /dev/null
then
  # install pyenv-virtualenv and source shell
  git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
  exec "$SHELL"
fi
printf "${GREEN}Success:${NC} Pyenv-virtualenv installed\n"

# install python (stable, most-recent 3.10)
pyenv install 3.10
printf "${GREEN}Success:${NC} Python 3.10 installed\n"

# setup virtualenv
pyenv virtualenv 3.10 bsc
printf "${GREEN}Success:${NC} Activated virtualenv\n"

# load requirements
pip install -r requirements.txt
printf "${GREEN}Success:${NC} All dependencies installed\n"

# make bash scripts executable
chmod +x setup
chmod +x train

# extract data
if [ -e src/data/processed.zip ]
then
  cd src/data
  unzip processed.zip && rm -rf processed.zip
  cd ../..
  printf "${GREEN}Success:${NC} Extracted processed data\n"
else 
  printf "${GREEN}Success:${NC} Data already extracted\n"
fi

printf "${GREEN}Success: ${NC}Environment setup\n"
